version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package1.zip .
      - zip -r9 ../deployment_package2.zip .
      - cd ..
      - zip -g deployment_package1.zip imageIndex.py
      - zip -g deployment_package2.zip imageSearch.py
  post_build:
    commands:
      - echo "Updating lambda Function 1..."
        #- aws lambda update-function-code --function-name index_photos --zip-file fileb://deployment_package1.zip
      - echo "Updating lambda Function 2..."
        #- aws lambda update-function-code --function-name search-photos --zip-file fileb://deployment_package2.zip
      - echo "DONE!!"
