version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    
  build:
    commands:
      - cd LF1
      - zip -r9 ../deployment_package1.zip .
      - cd ..
      - cd LF2
      - zip -r9 ../deployment_package2.zip .
  post_build:
    commands:
      - echo "Updating lambda Function 1..."
        #- aws lambda update-function-code --function-name index_photos --zip-file fileb://deployment_package1.zip
      - echo "Updating lambda Function 2..."
        #- aws lambda update-function-code --function-name search-photos --zip-file fileb://deployment_package2.zip
      - echo "DONE!!"
artifacts:
   files:
    - '**/*'
